//Alertas
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";
//Auth
export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
export const VERIFICACIOM_ENVIADA = "VERIFICACIOM_ENVIADA";
export const VERIFICACIOM_ERROR = "VERIFICACIOM_ERROR";
export const VERIFICADO = "VERIFICADO";
export const VERIFICADO_ERROR = "VERIFICADO_ERROR";
export const PASSWORD_RESET_EXITOSA = "PASSWORD_RESET_EXITOSA";
export const PASSWORD_RESET_ERROR = "PASSWORD_RESET_ERROR";
export const PASSWORD_CAMBIO_ERROR = "PASSWORD_CAMBIO_ERROR";
export const PASSWORD_CAMBIO_EXITO = "PASSWORD_CAMBIO_EXITO";
//users
export const BUSCAR_USUARIO = "BUSCAR_USUARIO";
export const BUSCAR_USUARIO_ERROR = "BUSCAR_USUARIO_ERROR";
export const GETUSER_REQUEST = "USER_GETUSER_REQUEST";
export const GETUSER_SUCCESS = "USER_GETUSER_SUCCESS";
export const GETUSER_FAILURE = "USER_GETUSER_FAILURE";
//post
export const NEW_POST = "NEW_POST";
export const POSTS_REQUEST = "POSTS_REQUEST";
export const POSTS_SUCCESS = "POSTS_SUCCESS";
export const POSTS_FAILURE = "POSTS_FAILURE";
export const LOCATION_POSTS_SUCCESS = "LOCATION_POSTS_SUCCESS";
export const HASHTAG_POSTS_REQUEST = "HASHTAG_POSTS_REQUEST";
export const LOCATION_POSTS_REQUEST = "LOCATION_POSTS_REQUEST";

export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILURE = "ADD_POST_FAILURE";
export const POST_DELETE_SUCCESS = "POSTS_DELETE_SUCCESS";
export const POST_DELETE_FAILURE = "POSTS_DELETE_FAILURE";
export const LIKE_POST = "LIKE_POST";
export const LIKE_POST_ERROR = "LIKE_POST_ERROR";
export const DISLIKE_POST = "DISLIKE_POST";
export const DISLIKE_POST_ERROR = "DISLIKE_POST_ERROR";
export const GET_POST_LIKES = "GET_POST_LIKES";
export const INIT_COMMENT = "INIT_COMMENT";
export const INIT_COMMENT_ERROR = "INIT_COMMENT_ERROR";
export const PUBLICACION_ACTUAL = "PUBLICACION_ACTUAL";
export const LIKE = "LIKE";
export const LIKE_ERROR = "LIKE_ERROR";

export const GET_POST = "GET_POST";
export const GET_POST_ERROR = "GET_POST_ERROR";

//edit post page
export const IMAGE_CROP_SELECT = "IMAGE_CROP_SELECT";
export const IMAGE_SELECT = "IMAGE_SELECT";
export const MAP_LOCATION_SELECT = "MAP_LOCATION_SELECT";
export const CANVAS_HAS_VALUE = "CANVAS_HAS_VALUE";
//imagenes cloudinary
export const PHOTOS_FETCHED = "PHOTOS_FETCHED";
export const PHOTOS_UPLOADED = "PHOTOS_UPLOADED";
export const DELETE_UPLOADED_PHOTO = "DELETE_UPLOADED_PHOTO";
export const UPDATE_UPLOADED_PHOTO = "UPDATE_UPLOADED_PHOTO";
//-Recordatorios
export const ADD_RECORDATORIO_SUCCESS = "ADD_RECORDATORIO_SUCCESS";
export const ADD_RECORDATORIO_FAILURE = "ADD_RECORDATORIO_FAILURE";
export const RECORDATORIO_DELETE_SUCCESS = "RECORDATORIO_DELETE_SUCCESS";
export const RECORDATORIO_DELETE_FAILURE = "RECORDATORIO_DELETE_FAILURE";
export const EDIT_RECORDATORIO_SUCCESS = "EDIT_RECORDATORIO_SUCCESS";
export const EDIT_RECORDATORIO_FAILURE = "EDIT_RECORDATORIO_FAILURE";
export const GET_RECORDATORIO_FAILURE = "GET_RECORDATORIO_FAILURE";
export const GET_RECORDATORIO_SUCCESS = "GET_RECORDATORIO_SUCCESS";
//-Anuncios
export const ADD_ANUNCIOS_SUCCESS = "ADD_ANUNCIOS_SUCCESS";
export const ADD_ANUNCIOS_FAILURE = "ADD_ANUNCIOS_FAILURE";
export const ANUNCIOS_DELETE_SUCCESS = "ANUNCIOS_DELETE_SUCCESS";
export const ANUNCIOS_DELETE_FAILURE = "ANUNCIOS_DELETE_FAILURE";
export const EDIT_ANUNCIOS_SUCCESS = "EDIT_ANUNCIOS_SUCCESS";
export const EDIT_ANUNCIOS_FAILURE = "EDIT_ANUNCIOS_FAILURE";
export const GET_ANUNCIOS_FAILURE = "GET_ANUNCIOS_FAILURE";
export const GET_ANUNCIOS_SUCCESS = "GET_ANUNCIOS_SUCCESS";
//-EVENTOS
export const ADD_EVENTOS_SUCCESS = "ADD_EVENTOS_SUCCESS";
export const ADD_EVENTOS_FAILURE = "ADD_EVENTOS_FAILURE";
export const EVENTOS_DELETE_SUCCESS = "EVENTOS_DELETE_SUCCESS";
export const EVENTOS_DELETE_FAILURE = "EVENTOS_DELETE_FAILURE";
export const EDIT_EVENTOS_SUCCESS = "EDIT_EVENTOS_SUCCESS";
export const EDIT_EVENTOS_FAILURE = "EDIT_EVENTOS_FAILURE";
export const GET_EVENTOS_FAILURE = "GET_EVENTOS_FAILURE";
export const GET_EVENTOS_SUCCESS = "GET_EVENTOS_SUCCESS";
