//Alertas
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";
//Auth
export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
export const VERIFICACIOM_ENVIADA = "VERIFICACIOM_ENVIADA";
export const VERIFICACIOM_ERROR = "VERIFICACIOM_ERROR";
export const VERIFICADO = "VERIFICADO";
export const VERIFICADO_ERROR = "VERIFICADO_ERROR";
export const PASSWORD_RESET_EXITOSA = "PASSWORD_RESET_EXITOSA";
export const PASSWORD_RESET_ERROR = "PASSWORD_RESET_ERROR";
export const PASSWORD_CAMBIO_ERROR = "PASSWORD_CAMBIO_ERROR";
export const PASSWORD_CAMBIO_EXITO = "PASSWORD_CAMBIO_EXITO";
//users
export const BUSCAR_USUARIO = "BUSCAR_USUARIO";
export const BUSCAR_USUARIO_ERROR = "BUSCAR_USUARIO_ERROR";
export const GETUSER_REQUEST = "USER_GETUSER_REQUEST";
export const GETUSER_SUCCESS = "USER_GETUSER_SUCCESS";
export const GETUSER_FAILURE = "USER_GETUSER_FAILURE";
export const GETALLUSER_SUCCESS = "GETALLUSER_SUCCESS";
export const GETALLUSER_FAILURE = "GETALLUSER_FAILURE";
export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS";
export const FOLLOW_FAILURE = "FOLLOW_FAILURE";
export const UNFOLLOW_SUCCESS = "UNFOLLOW_SUCCESS";
export const UNFOLLOW_FAILURE = "UNFOLLOW_FAILURE";
export const GETUSERSEARCH_SUCCESS = "GETUSERSEARCH_SUCCESS";
export const GETUSERSEARCH_FAILURE = "GETUSERSEARCH_FAILURE";
//post
export const NEW_POST = "NEW_POST";
export const POSTS_REQUEST = "POSTS_REQUEST";
export const POSTS_SUCCESS = "POSTS_SUCCESS";
export const POSTS_FAILURE = "POSTS_FAILURE";
export const LOCATION_POSTS_SUCCESS = "LOCATION_POSTS_SUCCESS";
export const HASHTAG_POSTS_REQUEST = "HASHTAG_POSTS_REQUEST";
export const LOCATION_POSTS_REQUEST = "LOCATION_POSTS_REQUEST";

export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILURE = "EDIT_POST_FAILURE";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_FAILURE = "ADD_POST_FAILURE";
export const POST_DELETE_SUCCESS = "POSTS_DELETE_SUCCESS";
export const POST_DELETE_FAILURE = "POSTS_DELETE_FAILURE";
export const LIKE_POST = "LIKE_POST";
export const LIKE_POST_ERROR = "LIKE_POST_ERROR";
export const DISLIKE_POST = "DISLIKE_POST";
export const DISLIKE_POST_ERROR = "DISLIKE_POST_ERROR";
export const GET_POST_LIKES = "GET_POST_LIKES";
export const INIT_COMMENT = "INIT_COMMENT";
export const INIT_COMMENT_ERROR = "INIT_COMMENT_ERROR";
export const DELETE_COMMENT = "INIT_COMMENT";
export const DELETE_COMMENT_ERROR = "INIT_COMMENT_ERROR";
export const PUBLICACION_ACTUAL = "PUBLICACION_ACTUAL";
export const LIKE = "LIKE";
export const LIKE_ERROR = "LIKE_ERROR";

export const GET_POST = "GET_POST";
export const GET_POST_ERROR = "GET_POST_ERROR";

//edit post page
export const IMAGE_CROP_SELECT = "IMAGE_CROP_SELECT";
export const IMAGE_SELECT = "IMAGE_SELECT";
export const MAP_LOCATION_SELECT = "MAP_LOCATION_SELECT";
export const CANVAS_HAS_VALUE = "CANVAS_HAS_VALUE";
//imagenes cloudinary
export const PHOTOS_FETCHED = "PHOTOS_FETCHED";
export const PHOTOS_UPLOADED = "PHOTOS_UPLOADED";
export const DELETE_UPLOADED_PHOTO = "DELETE_UPLOADED_PHOTO";
export const UPDATE_UPLOADED_PHOTO = "UPDATE_UPLOADED_PHOTO";
//-Recordatorios
export const ADD_RECORDATORIO_SUCCESS = "ADD_RECORDATORIO_SUCCESS";
export const ADD_RECORDATORIO_FAILURE = "ADD_RECORDATORIO_FAILURE";
export const RECORDATORIO_DELETE_SUCCESS = "RECORDATORIO_DELETE_SUCCESS";
export const RECORDATORIO_DELETE_FAILURE = "RECORDATORIO_DELETE_FAILURE";
export const EDIT_RECORDATORIO_SUCCESS = "EDIT_RECORDATORIO_SUCCESS";
export const EDIT_RECORDATORIO_FAILURE = "EDIT_RECORDATORIO_FAILURE";
export const GET_RECORDATORIO_FAILURE = "GET_RECORDATORIO_FAILURE";
export const GET_RECORDATORIO_SUCCESS = "GET_RECORDATORIO_SUCCESS";
//-Anuncios
export const ADD_ANUNCIOS_SUCCESS = "ADD_ANUNCIOS_SUCCESS";
export const ADD_ANUNCIOS_FAILURE = "ADD_ANUNCIOS_FAILURE";
export const ANUNCIOS_DELETE_SUCCESS = "ANUNCIOS_DELETE_SUCCESS";
export const ANUNCIOS_DELETE_FAILURE = "ANUNCIOS_DELETE_FAILURE";
export const EDIT_ANUNCIOS_SUCCESS = "EDIT_ANUNCIOS_SUCCESS";
export const EDIT_ANUNCIOS_FAILURE = "EDIT_ANUNCIOS_FAILURE";
export const GET_ANUNCIOS_FAILURE = "GET_ANUNCIOS_FAILURE";
export const GET_ANUNCIOS_SUCCESS = "GET_ANUNCIOS_SUCCESS";
export const ANUNCIO_FAILURE = "ANUNCIO_FAILURE";
export const ANUNCIO_SUCCESS = "ANUNCIO_SUCCESS";

//-EVENTOS
export const ADD_EVENTOS_SUCCESS = "ADD_EVENTOS_SUCCESS";
export const ADD_EVENTOS_FAILURE = "ADD_EVENTOS_FAILURE";
export const EVENTOS_DELETE_SUCCESS = "EVENTOS_DELETE_SUCCESS";
export const EVENTOS_DELETE_FAILURE = "EVENTOS_DELETE_FAILURE";
export const EDIT_EVENTOS_SUCCESS = "EDIT_EVENTOS_SUCCESS";
export const EDIT_EVENTOS_FAILURE = "EDIT_EVENTOS_FAILURE";
export const GET_EVENTOS_FAILURE = "GET_EVENTOS_FAILURE";
export const GET_EVENTOS_SUCCESS = "GET_EVENTOS_SUCCESS";
export const EVENTO_SUCCESS = "EVENTO_SUCCESS";
export const EVENTO_FAILURE = "EVENTO_FAILURE";
//-MASCOTAS
export const ADD_MASCOTAS_SUCCESS = "ADD_MASCOTAS_SUCCESS";
export const ADD_MASCOTAS_FAILURE = "ADD_MASCOTAS_FAILURE";
export const MASCOTAS_DELETE_SUCCESS = "MASCOTAS_DELETE_SUCCESS";
export const MASCOTAS_DELETE_FAILURE = "MASCOTAS_DELETE_FAILURE";
export const EDIT_MASCOTAS_SUCCESS = "EDIT_MASCOTAS_SUCCESS";
export const EDIT_MASCOTAS_FAILURE = "EDIT_MASCOTAS_FAILURE";
export const GET_MASCOTAS_FAILURE = "GET_MASCOTAS_FAILURE";
export const GET_MASCOTAS_SUCCESS = "GET_MASCOTAS_SUCCESS";
export const GET_MASCOTA_FAILURE = "GET_MASCOTA_FAILURE";
export const GET_MASCOTA_SUCCESS = "GET_MASCOTA_SUCCESS";
//PERFIL
export const EDIT_PERFIL_SUCCESS = "EDIT_PERFIL_SUCCESS";
export const EDIT_PERFIL_FAILURE = "EDIT_PERFIL_FAILURE";
export const EDIT_FOTOPERFIL_SUCCESS = "EDIT_FOTOPERFIL_SUCCESS";
export const EDIT_FOTOPERFIL_FAILURE = "EDIT_FOTOPERFIL_FAILURE";
//Negocio
export const ADD_NEGOCIOS_SUCCESS = "ADD_NEGOCIOS_SUCCESS";
export const ADD_NEGOCIOS_FAILURE = "ADD_NEGOCIOS_FAILURE";
export const NEGOCIOS_DELETE_SUCCESS = "NEGOCIOS_DELETE_SUCCESS";
export const NEGOCIOS_DELETE_FAILURE = "NEGOCIOS_DELETE_FAILURE";
export const EDIT_NEGOCIOS_SUCCESS = "EDIT_NEGOCIOS_SUCCESS";
export const EDIT_NEGOCIOS_FAILURE = "EDIT_NEGOCIOS_FAILURE";
export const GET_NEGOCIOS_FAILURE = "GET_NEGOCIOS_FAILURE";
export const GET_NEGOCIOS_SUCCESS = "GET_NEGOCIOS_SUCCESS";
export const NEGOCIO_FAILURE = "NEGOCIO_FAILURE";
export const NEGOCIO_SUCCESS = "NEGOCIO_SUCCESS";
//socket  io
export const CONNECT = "CONNECT";
// chat
export const HANGE_ROOM = "CHANGE_ROOM";
export const INIT_MESSAGE_ARRAY = "INIT_MESSAGE_ARRAY";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const READ_MESSAGES = "READ_MESSAGES";
export const RECEIVE_READ_MESSAGES = "RECEIVE_READ_MESSAGES";
export const CHANGE_ACTIVITY_STATUS = "CHANGE_ACTIVITY_STATUS";
export const ADD_NEW_ROOM = "ADD_NEW_ROOM";
export const INC_MESSAGE_COUNT = "INC_MESSAGE_COUNT";
export const SEARCH_USERS = "SEARCH_USERS";
export const OPEN_CALLING_MODAL = "OPEN_CALLING_MODAL";
export const CLOSE_CALLING_MODAL = "CLOSE_CALLING_MODAL";
export const NEW_ANSWER = "NEW_ANSWER";
export const OPEN_ANSWERING_MODAL = "OPEN_ANSWERING_MODAL";
export const CLOSE_ANSWERING_MODAL = "CLOSE_ANSWERING_MODAL";
export const TYPING = "TYPING";
export const STOPPED_TYPING = "STOPPED_TYPING";
export const GET_ROOMS_REQUEST = "GET_ROOMS_REQUEST";
export const GET_ROOMS_SUCCESS = "GET_ROOMS_SUCCESS";
export const GET_MESSAGES_INITIAL_REQUEST = "GET_MESSAGES_INITIAL_REQUEST";
export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const NEW_IMAGE_MESSAGE_REQUEST = "NEW_IMAGE_MESSAGE_REQUEST";
export const NEW_IMAGE_MESSAGE_SUCCESS = "NEW_IMAGE_MESSAGE_SUCCESS";
//notificaciones
export const TOGGLE_NOTIFICATION_POPUP = "TOGGLE_NOTIFICATION_POPUP";
export const CLOSE_NOTIFICATION_POPUP = "CLOSE_NOTIFICATION_POPUP";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const READ_NOTIFICATIOS = "READ_NOTIFICATIOS";
export const FETCH_NOTIFICATIONS_REQUEST = "FETCH_NOTIFICATIONS_REQUEST";
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
